name:                intel8080
version:             0.0.0.0
synopsis:            "Intel 8080 CPU core: software emulator and CLaSH hardware description"
homepage:            https://github.com/gergoerdi/clash-intel8080
license:             MIT
author:              Gergő Érdi
maintainer:          gergo@erdi.hu
copyright:           2019 Gergő Érdi
category:            Hardware

extra-source-files:
  - LICENSE
  - README.md

dependencies:
  - base >= 4.7 && < 5
  - clash-prelude
  - clash-retrocomputer-utils
  - bytestring
  - mtl
  - transformers
  - containers
  - array
  - lens
  - generic-lens >= 1.1 && < 1.2
  - singletons
  - extra
  - monad-loops
  - higgledy >= 0.3 && < 0.4
  - barbies >= 1.1 && < 1.2
  - ghc-typelits-natnormalise
  - ghc-typelits-extra
  - ghc-typelits-knownnat

source-dirs:
  - src

ghc-options:
  -fexpose-all-unfoldings -fno-worker-wrapper
  -fplugin GHC.TypeLits.KnownNat.Solver
  -fplugin GHC.TypeLits.Normalise
  -fplugin GHC.TypeLits.Extra.Solver

library:
  exposed-modules:
    - Hardware.Intel8080
    - Hardware.Intel8080.ISA
    - Hardware.Intel8080.ALU
    - Hardware.Intel8080.Decode
    - Hardware.Intel8080.Microcode
    - Hardware.Intel8080.TestBench

    - Hardware.Emulator.Memory
    - Hardware.Emulator.Intel8080.CPU

    - Hardware.Clash.Intel8080.CPU
    - Hardware.Clash.Intel8080.Interruptor
    - Hardware.Clash.Intel8080.Sim

executables:
  test-bench-sim:
    main:             Hardware.Clash.Intel8080.TestBench

  test-bench-emu:
    main:             Hardware.Emulator.Intel8080.TestBench
