name:                intel8080
version:             0.0.0.0
synopsis:            "Intel 8080 CPU core: software emulator and CLaSH hardware description"
homepage:            https://github.com/gergoerdi/clash-intel8080
license:             MIT
author:              Gergő Érdi
maintainer:          gergo@erdi.hu
copyright:           2019 Gergő Érdi
category:            Hardware

extra-source-files:
  - LICENSE
  - README.md

dependencies:
  - base >= 4.7 && < 5
  - clash-prelude
  - ghc-typelits-natnormalise
  - ghc-typelits-extra
  - ghc-typelits-knownnat

  - retroclash-lib

  - bytestring
  - mtl
  - transformers
  - barbies ^>= 2.0.1
  - barbies-th
  - containers
  - array
  - lens
  - singletons
  - extra
  - monad-loops

# Anything that Clash uses by default should go here
default-extensions:
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DeriveAnyClass
  - DeriveGeneric
  - DeriveLift
  - DerivingStrategies
  - ExplicitForAll
  - ExplicitNamespaces
  - FlexibleContexts
  - FlexibleInstances
  - KindSignatures
  - MagicHash
  - MonoLocalBinds
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - NoStarIsType
  - NoStrictData
  - NoStrict
  - QuasiQuotes
  - ScopedTypeVariables
  - TemplateHaskellQuotes
  - TemplateHaskell
  - TypeApplications
  - TypeFamilies
  - TypeInType
  - TypeOperators

ghc-options:
  -fexpose-all-unfoldings -fno-worker-wrapper
  -fplugin GHC.TypeLits.KnownNat.Solver
  -fplugin GHC.TypeLits.Normalise
  -fplugin GHC.TypeLits.Extra.Solver

source-dirs:
  - src

library:
  exposed-modules:
    - Hardware.Intel8080
    - Hardware.Intel8080.Model
    - Hardware.Intel8080.CPU
    - Hardware.Intel8080.Interruptor

data-files:
  - image/*/*.com
  - image/*/*.COM

tests:
  test-model:
    source-dirs: test
    main: test-model.hs
    dependencies:
      - tasty
      - tasty-golden
      - filepath

  test-sim:
    source-dirs: test
    main: test-sim.hs
    dependencies:
      - tasty
      - tasty-golden
      - filepath

executables:
  tinybasic-model:
    source-dirs: test
    main: tinybasic-model.hs
    dependencies:
      - terminal
