resolver: clash-HEAD.yaml

extra-deps:
  - barbies-2.0.1.0
  - barbies-th-0.1.2

  - github: emilypi/smash
    commit: bd3ae30bdfef3f92ce5575a1ee10228830afa11b
    subdirs:
      - smash-core

packages:
  - retroclash-lib
  - .
